apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-empty-version
  namespace: 03-empty-version
spec:
  releaseName: redis-empty-version
  interval: 10m
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: apps