apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: web-app
data:
  app.properties: |
    server.port=8080
    database.url=jdbc:postgresql://db:5432/myapp
    logging.level=INFO
    feature.enabled=true
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
        
        location /api/ {
            proxy_pass http://backend:8080/;
        }
    }

