apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  labels:
    app: migration
spec:
  backoffLimit: 3
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: migration
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: migrate/migrate:v4.15.2
        command:
        - migrate
        - -path
        - /migrations
        - -database
        - postgres://dbuser:password123@database:5432/myapp?sslmode=disable
        - up
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-password

