apiVersion: v1
kind: Pod
metadata:
  name: standalone-pod
  labels:
    app: standalone
    tier: backend
spec:
  containers:
  - name: app-container
    image: alpine:latest
    command: ["sh", "-c", "echo 'Hello from standalone pod' && sleep 3600"]
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "64Mi"
        cpu: "200m"
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  restartPolicy: Always

