apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: web-app
type: Opaque
data:
  # base64 encoded values
  database-password: cGFzc3dvcmQxMjM=  # password123
  api-key: YWJjZGVmZ2hpams=           # abcdefghijk
  jwt-secret: bXlzZWNyZXRrZXk=       # mysecretkey
stringData:
  # plain text values (will be encoded automatically)
  username: myuser
  email: admin@example.com

