apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-test.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.enableMetrics }}
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "agent-test.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent-test.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-test.labels" . | nindent 4 }}
data:
  app.properties: |
    test.mode={{ .Values.testMode }}
    log.level={{ .Values.logLevel }}
    metrics.enabled={{ .Values.enableMetrics }}
    {{- range .Values.agent.testing.scenarios }}
    scenario.{{ . }}=enabled
    {{- end }}
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 80;
            location / {
                add_header X-Chart-Version "{{ .Chart.Version }}";
                add_header X-Release-Name "{{ .Release.Name }}";
                add_header X-Test-Mode "{{ .Values.testMode }}";
                root /usr/share/nginx/html;
                index index.html;
            }
            {{- if .Values.enableMetrics }}
            location /metrics {
                access_log off;
                return 200 "# HELP helm_test_metric Helm test metric\n# TYPE helm_test_metric counter\nhelm_test_metric{release=\"{{ .Release.Name }}\",chart=\"{{ .Chart.Name }}\"} 1\n";
                add_header Content-Type text/plain;
            }
            {{- end }}
        }
    }

